#!/bin/bash

CHANNEL=$1

if [ -z "$CHANNEL" ]; then
	echo "Usage : dbus-talk <channel>" >&2
	exit 1
fi


while read CONTENT; do
	dbus-send --type=signal / org.marcel.dbus.talk.$CHANNEL string:"##${CONTENT}"
done