#!/bin/bash

CHANNEL=$1

if [ -z "$CHANNEL" ]; then
	echo "Usage : dbus-listen <channel>" >&2
	exit 1
fi

dbus-monitor "interface='org.marcel.dbus.talk',member='${CHANNEL}'" | while read LINE; do
	echo $LINE | grep --color=never -oP '(?<="##).*(?=")'
done